name: Start Fetching

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'
    
permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer script
        run: npm run fetch

      - name: Commit result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add winrate.json
          git commit -m "Winrate update" || echo "No changes to commit"
          git push origin HEAD
